//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiodeMnf
    {
        public string Mfr__Name { get; set; }
        public string Mfr__Part_Number { get; set; }
        public string Part_Status { get; set; }
        public string RoHS_Status { get; set; }
        public string Comments { get; set; }
        public string Type { get; set; }
        public int M_Id { get; set; }
        public int Id { get; set; }
    
        public virtual Diode Diode { get; set; }
    }
}
