//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oscillator
    {
        public Oscillator()
        {
            this.OscillatorsMnfs = new HashSet<OscillatorsMnf>();
        }
    
        public string BOM_Number { get; set; }
        public string BU { get; set; }
        public string Product_line { get; set; }
        public string Site { get; set; }
        public int Thermo_Number { get; set; }
        public string Item_Description { get; set; }
        public string Category { get; set; }
        public string Part { get; set; }
        public string Part_Type { get; set; }
        public string Frequency { get; set; }
        public string Freq____Tolerance { get; set; }
        public string Frequency___Stability { get; set; }
        public string Load___Capacitance { get; set; }
        public string Mounting { get; set; }
        public string Operating___Temp { get; set; }
        public string Dimensions { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<OscillatorsMnf> OscillatorsMnfs { get; set; }
    }
}
