//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relay
    {
        public Relay()
        {
            this.RelayMnfs = new HashSet<RelayMnf>();
        }
    
        public string BOM_Number { get; set; }
        public string BU { get; set; }
        public string Product_line { get; set; }
        public string Site { get; set; }
        public int Thermo_Number { get; set; }
        public string Item_Description { get; set; }
        public string Category { get; set; }
        public string Part { get; set; }
        public string Part_Type { get; set; }
        public string Form___Factor { get; set; }
        public double Current___Rating_A { get; set; }
        public string Coil___Rating { get; set; }
        public Nullable<double> Coil___Resistance { get; set; }
        public string Contact___Configuration { get; set; }
        public string Operating___Temperature { get; set; }
        public string Mounting___Style { get; set; }
        public string Dimensions { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<RelayMnf> RelayMnfs { get; set; }
    }
}
