//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transformer
    {
        public Transformer()
        {
            this.TransformerMnfs = new HashSet<TransformerMnf>();
        }
    
        public string BOM_Number { get; set; }
        public string BU { get; set; }
        public string Product_line { get; set; }
        public string Site { get; set; }
        public int Thermo_Number { get; set; }
        public string Item_Description { get; set; }
        public string Category { get; set; }
        public string Part { get; set; }
        public string Part_Type { get; set; }
        public string Turns_Ratio { get; set; }
        public string Power_rating { get; set; }
        public string Mounting_Style { get; set; }
        public string Max_Temp { get; set; }
        public string Dimensions { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<TransformerMnf> TransformerMnfs { get; set; }
    }
}
